const canvas = document.getElementById("scene"),
    touchControls = document.getElementsByClassName("touch-controls")[0],
    leftButton = document.querySelector(".left-button"),
    rightButton = document.querySelector(".right-button"),
    upButton = document.querySelector(".up-button"),
    buttons = document.querySelector(".buttons"),
    helpBtn = document.querySelector(".help"),
    contactBtn = document.querySelector(".contact"),
    aboutBtn = document.querySelector(".about");